### PR TITLE
Github Actions for CI

### PR DESCRIPTION
**Pull request by janklimo**
I took a shot at moving the CI pipeline to Github Actions to see if it adds value to the project. Seeing two benefits right now:

1. Faster builds. Taking less than 30 minutes ([example](https://github.com/janklimo/ranked-model/commit/27a68fb838e593ed6b98551caf6f0e1c2aef3530/checks?check_suite_id=395429930)), so faster than Travis despite running more jobs.
1. More flexibility defining services. E.g. testing on MySQL 8 which isn't available on Travis afaik.

**Notable changes:**

1. Updated lockfiles and moved them back into version control. This is to enable caching in CI based on checksums of these files.
1. Added Ruby 2.7 to the matrix.

**Future work:**

1. Couldn't make MySQL work with JRuby. Since I don't use either of those, it would be nice to get help from contributors who do.
1. Testing on MySQL 8 breaks due to invalid SQL. Again, I'd like to get eyes on it from some MySQL users.

Screen Shot 2020-01-11 at 5 51 58 PM

Interested in migrating or sticking to Travis?

### CODE REVIEW

**Comment by brendon** [comment]
Thank you @janklimo, this is great work. I'm definitely happy to switch if it's faster than travis. I'm currently on holiday at the moment but will mark this to look at once I return in a week or so. Feel free to update things if you find solutions to any of your problems :)

**Comment by brendon** [comment]
Hi @janklimo, for jruby, I think you just need to use the correct version of the https://github.com/jruby/activerecord-jdbc-adapter gem vs Rails version. Same goes for Postgres and sqlite I think.

For the SQL error, I don't use MySQL with this gem either, but my hunch is that that integer value is outside of the default limits for MySQL 8? Though you'd think the error would be different :)

Are you happy to keep tapping away at this one?

**Comment by brendon** [comment]
https://stackoverflow.com/a/17783287/129798

**Comment by brendon** [comment]
Hi @janklimo, just checking you're abandoning this one? :)

**Comment by janklimo** [comment]
Hi @brendon yup, cleaning up my PR list. Unfortunately won't have the time to focus on this.

**Comment by brendon** [comment]
I know the feeling!

**Pull request closed without merging**
