### PR TITLE
Update Travis matrix with modern ruby & rails versions

### PR DESCRIPTION
**Pull request by nextmat**
Update text matrix for modern rubies / rails.

### CODE REVIEW

**Comment by nextmat** [comment]
There are failures on a number of the postgres builds that look like they may be real. Otherwise this looks like it is running clean.

**Comment by nextmat** [comment]
Nevermind looks like postgres isn't supported on 3.2, will fix.

**Comment by nextmat** [comment]
This is now running clean.

**Comment by mixonic** [comment]
👍 I'll likely bump to 0.5.0 since we've stopped testing older rubies.

**Comment by nextmat** [comment]
> 👍 I'll likely bump to 0.5.0 since we've stopped testing older rubies.

Yeah the only real drop is 1.9.2 - I did that assuming that anyone on 1.9.2 in production has probably moved to 1.9.3 by now but could add it back if you think it is important?

**Comment by mixonic** [comment]
I don't think it is important at this date, not if we bump the minor.

**Pull request merged**
