### PR TITLE
added Rails6 to CI

### PR DESCRIPTION
**Pull request by walf443**
Rails 6.0.0rc2 was released.
https://weblog.rubyonrails.org/2019/7/30/Rails-6-0-rc2-released/

I'd like to check this gem working with Rails6 before it will be released.

### CODE REVIEW

**Comment by brendon** [comment]
Hi @walf443, thanks for your persistence with this! :) Nearly there it would seem. Just an incompatibility with Postgres and Rails 6. Can you change the travis config to use a newer Postgres? I guess it'll have to be one that works backward with the old versions of Rails too.

Also, your code formatter has had a field day with brackets. Personally I prefer not to bracket arguments. Can you revert those changes as that just adds noise to the PR. :)

**Comment by walf443** [comment]
@brendon Does it mean reverting update_attribute changes? or update_attribute is OK, but coding style is not ok, so fix it?

update_attribute changes is for Depreaction warnings for Rails 6.1. 
https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/

**Comment by brendon** [comment]
Sorry I didn't notice that :) Yes `update` is fine, but just remove the brackets :)

**Comment by brendon** [comment]
You could try this instead: https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version

**Comment by brendon** [comment]
This is proving to be a painful one! :)

**Comment by brendon** [comment]
I restarted the one failing test.

We shouldn't have to override from peer to md5 if we just connect to the database using the correct user. Has that user changed?

**Comment by walf443** [comment]
That code does not exist, it cannot connect by postgresql user. See also https://github.com/travis-ci/travis-ci/issues/9624#issuecomment-389537036

**Comment by brendon** [comment]
I see :) Looks like the latest commit broke the build. The one before it seemed ok though :)

**Comment by brendon** [comment]
Just checking, do we need Postgres 10? Or can we get away with the latest 9?

**Comment by walf443** [comment]
@brendon Postgresq10 need for Rails6. Rails 6 postgresql adapter does not suport postgresql 9.

**Comment by walf443** [comment]
see https://travis-ci.org/mixonic/ranked-model/jobs/571110005 

```
RuntimeError:
  Your version of PostgreSQL (90224) is too old. Active Record supports PostgreSQL >= 9.3.
# ./gemfiles/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_adapters/postgresql_adapter.rb:457:in `check_version'
```

**Comment by brendon** [comment]
You could use Postgres 9.6.15?

**Comment by walf443** [comment]
https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-263550556 hmm. OK. I'll try it.

**Comment by brendon** [comment]
Talk about a long haul! Thank you so much @walf443 for your persistence on this one. Many would have long ago abandoned the effort! :)

I'll merge this quickly before it turns red again!! :D

**Pull request merged**
