### PR TITLE
drop old ruby support on CI

### PR DESCRIPTION
**Pull request by walf443**
CI time is too long to wait. I'm happy to reduce test matrix.

ruby 2.3.0 was already EOL. 
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

ruby 2.3 is left bacause of Rails4.x testing.
I think Rails4.x can also drop support from next release.

### CODE REVIEW

**Comment by walf443** [comment]
No code are exist that is not working old ruby version.
But adding required_ruby_version to gem spec is better for compatibility for old ruby users.

https://guides.rubygems.org/specification-reference/#required_ruby_version

**Comment by brendon** [comment]
Good call. I think we should keep Rails 4.2 testing. Apparently Rails 4.2 supports Ruby 2.4.5.

**Comment by brendon** [comment]
Sorry, reading between my lines, let's keep Rails 4.2 but drop Ruby 2.3.

**Comment by walf443** [comment]
@brendon Do you mean drop Rails v4.1 support on this PR?

**Comment by brendon** [comment]
Yes I think so. 4.2 is the only one currently supported by Rails. I'm happy to keep Rails 4.2 support for a year or two after Rails drops support though as I've been in that position where I've been stuck on a slightly out of date version before.

**Comment by walf443** [comment]
https://github.com/mixonic/ranked-model/blob/master/ranked-model.gemspec#L16 activerecord dependency should be upgrade to 4.2?

**Comment by brendon** [comment]
Yes that's a good idea :)

**Comment by walf443** [comment]
@brendon CI passed!

**Comment by brendon** [comment]
Choice! :)

**Pull request merged**
