### PR TITLE
Update Travis build matrix to supported versions

### PR DESCRIPTION
**Pull request by kereyroper**

### CODE REVIEW

**Comment by mixonic** [comment]
@kereyroper why are the versions you've dropped here unsupported?

**Comment by kereyroper** [comment]
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

http://guides.rubyonrails.org/maintenance_policy.html
"Currently included series: 5.0.Z, 4.2.Z."

**Comment by mixonic** [comment]
@kereyroper that seems good enough justification to me. Merging and the next bump will be 0.5.0.

**Comment by mixonic** [comment]
(merging pending a green build, just kicked off a retry)

**Comment by kereyroper** [comment]
Couldn't sort out what Travis wants for Rubinius, but otherwise passing with that removed.

**Comment by kereyroper** [comment]
@mixonic Should be good to merge. Rubinius on Travis appears broken for more than just this project.

**Comment by petergoldstein** [comment]
@mixonic Would love to see this merged with a new gem version.  Agree with @kereyroper that Rubinius on Travis seems non-functional at this point, so removing it from the matrix should be a non-issue

**Comment by brendon** [comment]
@mixonic, we removed Rubinius testing for `acts_as_list` for the same reason.

**Comment by brendon** [comment]
This has all been resolved in master.

**Pull request closed without merging**
