### PR TITLE
Test with Rails 6.1

### PR DESCRIPTION
**Pull request by aried3r**
Hope this works. Still not GitHub Actions and still using EOL JRuby 9.1.

If possible, could the description of the gem also be changed to say that it's a replacement for Rails 4, 5 and 6 instead of 3 and 4 like it does now?

### CODE REVIEW

**Comment by brendon** [comment]
Thanks @aried3r :) I'll update the description. Much appreciated :)

**Comment by brendon** [comment]
Actually I still don't own the project. @mixonic, are we able to sort that out? :)

**Comment by brendon** [comment]
@aried3r, the description has been updated now :)

**Comment by aried3r** [comment]
Awesome, thank you! And @mixonic, too!

**Pull request merged**
