### PR TITLE
use xenial distribution instead of trusty on travis CI testing

### PR DESCRIPTION
**Pull request by walf443**
#154 test failed cause of postgresql server is too old for Rails6.

So I'd like to update distribution of testing on travisCI for future.

### CODE REVIEW

**Comment by brendon** [comment]
Hehe, sorry I replied to another thread. Just check in on the RBX packages. They probably just need updating to the latest version.

**Comment by brendon** [comment]
@walf443, can you ping me once this is green?  :)

**Comment by walf443** [comment]
OK. I see.

**Comment by walf443** [comment]
🤔

``` 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by brendon** [comment]
Seems to be stalling installing the `pg` gem :(

**Comment by brendon** [comment]
Rubinius does my head in! :) Tempted to drop it, but it's hard to say if people use it with this gem.

**Comment by walf443** [comment]
I changed CI settings on #154

**Pull request closed without merging**
